mappings:
  SWS_CheckoutTest: SwipeStripe\Core\tests\SWS_CheckoutTest
  SWS_OrderTest: SwipeStripe\Core\tests\SWS_OrderTest
  SWS_CartTest: SwipeStripe\Core\tests\SWS_CartTest
  SWS_Test: SwipeStripe\Core\tests\SWS_Test
  SWS_ProductTest: SwipeStripe\Core\tests\SWS_ProductTest
  SWS_AccountTest: SwipeStripe\Core\tests\SWS_AccountTest
  CheckoutPage: SwipeStripe\Core\Customer\CheckoutPage
  CheckoutPage_Controller: SwipeStripe\Core\Customer\CheckoutPageController
  CartPage: SwipeStripe\Core\Customer\CartPage
  CartPage_Controller: SwipeStripe\Core\Customer\CartPageController
  Customer: SwipeStripe\Core\Customer\Customer
  AccountPage: SwipeStripe\Core\Customer\AccountPage
  AccountPage_Controller: SwipeStripe\Core\Customer\AccountPageController
  Cart: SwipeStripe\Core\Customer\Cart
  Price: SwipeStripe\Core\Product\Price
  Attribute: SwipeStripe\Core\Product\Attribute
  Attribute_OptionField: SwipeStripe\Core\Product\AttributeOptionField
  Attribute_Default: SwipeStripe\Core\Product\AttributeDefault
  Variation: SwipeStripe\Core\Product\Variation
  Variation_Options: SwipeStripe\Core\Product\VariationOptions
  Product: SwipeStripe\Core\Product\Product
  Product_Controller: SwipeStripe\Core\Product\Product_Controller
  Option: SwipeStripe\Core\Product\Option
  Option_Default: SwipeStripe\Core\Product\OptionDefault
  Order: SwipeStripe\Core\Order\Order
  Order_Update: SwipeStripe\Core\Order\OrderUpdate
  ItemOption: SwipeStripe\Core\Order\ItemOption
  Modification: SwipeStripe\Core\Order\Modification
  Item: SwipeStripe\Core\Order\Item
  Payment_Extension: SwipeStripe\Core\Order\Payment_Extension
  Payment_ProcessorExtension: SwipeStripe\Core\Order\PaymentProcessorExtension
  ModificationField_Hidden: SwipeStripe\Core\Form\ModificationFieldHidden
  ModificationField_Dropdown: SwipeStripe\Core\Form\ModificationFieldDropdown
  CartForm: SwipeStripe\Core\Form\CartForm
  CartForm_QuantityField: SwipeStripe\Core\Form\CartFormQuantityField
  OrderForm: SwipeStripe\Core\Form\OrderForm
  OrderForm_Validator: SwipeStripe\Core\Form\OrderFormValidator
  OrderForm_ItemField: SwipeStripe\Core\Form\OrderFormItemField
  ProductForm: SwipeStripe\Core\Form\ProductForm
  ProductForm_Validator: SwipeStripe\Core\Form\ProductFormValidator
  ProductForm_QuantityField: SwipeStripe\Core\Form\ProductFormQuantityField
  RepayForm: SwipeStripe\Core\Form\RepayForm
  OptionField: SwipeStripe\Core\Admin\OptionField
  PriceField: SwipeStripe\Core\Admin\PriceField
  ShopSearchContext_Order: SwipeStripe\Core\Admin\ShopSearchContext_Order
  GridFieldDetailForm_HasManyItemRequest: SwipeStripe\Core\Admin\GridFieldDetailForm_HasManyItemRequest
  ShopConfig: SwipeStripe\Core\Admin\ShopConfig
  ShopSearchFilter_OptionSet: SwipeStripe\Core\Admin\ShopSearchFilterOptionSet
  ShopSearchFilter_PublishedStatus: SwipeStripe\Core\Admin\ShopSearchFilterPublishedStatus
  ShopAdmin: SwipeStripe\Core\Admin\ShopAdmin
  ShopAdmin_EmailAdmin: SwipeStripe\Core\Admin\ShopAdminEmailAdmin
  ShopAdmin_BaseCurrency: SwipeStripe\Core\Admin\ShopAdminBaseCurrency
  ShopAdmin_Attribute: SwipeStripe\Core\Admin\ShopAdminAttribute
  ShopAdmin_LeftAndMainExtension: SwipeStripe\Core\Admin\ShopAdminLeftAndMainExtension
  GridFieldConfig_Basic: SwipeStripe\Core\Admin\GridFieldConfig_Basic
  GridFieldConfig_BasicSortable: SwipeStripe\Core\Admin\GridFieldConfig_BasicSortable
  GridFieldConfig_HasManyRelationEditor: SwipeStripe\Core\Admin\GridFieldConfig_HasManyRelationEditor
  NotificationEmail: SwipeStripe\Core\Mails\NotificationEmail
  ProcessedEmail: SwipeStripe\Core\Mails\ProcessedEmail
  ReceiptEmail: SwipeStripe\Core\Mails\ReceiptEmail
  RemoveDevOrdersTask: SwipeStripe\Core\tasks\RemoveDevOrdersTask
  RemoveAbandonedCartsTask: SwipeStripe\Core\tasks\RemoveAbandonedCartsTask
