mappings:
  SWS_CheckoutTest: SwipeStripe\Core\tests\SWS_CheckoutTest
  SWS_OrderTest: SwipeStripe\Core\tests\SWS_OrderTest
  SWS_CartTest: SwipeStripe\Core\tests\SWS_CartTest
  SWS_Test: SwipeStripe\Core\tests\SWS_Test
  SWS_ProductTest: SwipeStripe\Core\tests\SWS_ProductTest
  SWS_AccountTest: SwipeStripe\Core\tests\SWS_AccountTest
  CheckoutPage: SwipeStripe\Core\code\Customer\CheckoutPage
  CheckoutPage_Controller: SwipeStripe\Core\code\Customer\CheckoutPage_Controller
  CartPage: SwipeStripe\Core\code\Customer\CartPage
  CartPage_Controller: SwipeStripe\Core\code\Customer\CartPage_Controller
  Customer: SwipeStripe\Core\code\Customer\Customer
  AccountPage: SwipeStripe\Core\code\Customer\AccountPage
  AccountPage_Controller: SwipeStripe\Core\code\Customer\AccountPage_Controller
  Cart: SwipeStripe\Core\code\Customer\Cart
  Price: SwipeStripe\Core\code\Product\Price
  Attribute: SwipeStripe\Core\code\Product\Attribute
  Attribute_OptionField: SwipeStripe\Core\code\Product\Attribute_OptionField
  Attribute_Default: SwipeStripe\Core\code\Product\Attribute_Default
  Variation: SwipeStripe\Core\code\Product\Variation
  Variation_Options: SwipeStripe\Core\code\Product\Variation_Options
  Product: SwipeStripe\Core\code\Product\Product
  Product_Controller: SwipeStripe\Core\code\Product\Product_Controller
  Option: SwipeStripe\Core\code\Product\Option
  Option_Default: SwipeStripe\Core\code\Product\Option_Default
  Order: SwipeStripe\Core\code\Order\Order
  Order_Update: SwipeStripe\Core\code\Order\Order_Update
  ItemOption: SwipeStripe\Core\code\Order\ItemOption
  Modification: SwipeStripe\Core\code\Order\Modification
  Item: SwipeStripe\Core\code\Order\Item
  Payment_Extension: SwipeStripe\Core\code\Order\Payment_Extension
  Payment_ProcessorExtension: SwipeStripe\Core\code\Order\Payment_ProcessorExtension
  ModificationField_Hidden: SwipeStripe\Core\code\Form\ModificationField_Hidden
  ModificationField_Dropdown: SwipeStripe\Core\code\Form\ModificationField_Dropdown
  CartForm: SwipeStripe\Core\code\Form\CartForm
  CartForm_QuantityField: SwipeStripe\Core\code\Form\CartForm_QuantityField
  OrderForm: SwipeStripe\Core\code\Form\OrderForm
  OrderForm_Validator: SwipeStripe\Core\code\Form\OrderForm_Validator
  OrderForm_ItemField: SwipeStripe\Core\code\Form\OrderForm_ItemField
  ProductForm: SwipeStripe\Core\code\Form\ProductForm
  ProductForm_Validator: SwipeStripe\Core\code\Form\ProductForm_Validator
  ProductForm_QuantityField: SwipeStripe\Core\code\Form\ProductForm_QuantityField
  RepayForm: SwipeStripe\Core\code\Form\RepayForm
  OptionField: SwipeStripe\Core\code\Admin\OptionField
  PriceField: SwipeStripe\Core\code\Admin\PriceField
  ShopSearchContext_Order: SwipeStripe\Core\code\Admin\ShopSearchContext_Order
  GridFieldDetailForm_HasManyItemRequest: SwipeStripe\Core\code\Admin\GridFieldDetailForm_HasManyItemRequest
  ShopConfig: SwipeStripe\Core\code\Admin\ShopConfig
  ShopSearchFilter_OptionSet: SwipeStripe\Core\code\Admin\ShopSearchFilter_OptionSet
  ShopSearchFilter_PublishedStatus: SwipeStripe\Core\code\Admin\ShopSearchFilter_PublishedStatus
  ShopAdmin: SwipeStripe\Core\code\Admin\ShopAdmin
  ShopAdmin_EmailAdmin: SwipeStripe\Core\code\Admin\ShopAdmin_EmailAdmin
  ShopAdmin_BaseCurrency: SwipeStripe\Core\code\Admin\ShopAdmin_BaseCurrency
  ShopAdmin_Attribute: SwipeStripe\Core\code\Admin\ShopAdmin_Attribute
  ShopAdmin_LeftAndMainExtension: SwipeStripe\Core\code\Admin\ShopAdmin_LeftAndMainExtension
  GridFieldConfig_Basic: SwipeStripe\Core\code\Admin\GridFieldConfig_Basic
  GridFieldConfig_BasicSortable: SwipeStripe\Core\code\Admin\GridFieldConfig_BasicSortable
  GridFieldConfig_HasManyRelationEditor: SwipeStripe\Core\code\Admin\GridFieldConfig_HasManyRelationEditor
  NotificationEmail: SwipeStripe\Core\code\Mails\NotificationEmail
  ProcessedEmail: SwipeStripe\Core\code\Mails\ProcessedEmail
  ReceiptEmail: SwipeStripe\Core\code\Mails\ReceiptEmail
  RemoveDevOrdersTask: SwipeStripe\Core\tasks\RemoveDevOrdersTask
  RemoveAbandonedCartsTask: SwipeStripe\Core\tasks\RemoveAbandonedCartsTask
